// Generates supabase/seed.sql from content/rooms.json (the single source of truth).
// Usage: npm run seed:gen
import { readFileSync, writeFileSync } from "node:fs";

const { rooms } = JSON.parse(readFileSync("content/rooms.json", "utf8"));
const q = (v) => (v == null ? "null" : `'${String(v).replaceAll("'", "''")}'`);

const lines = [
  "-- GENERATED by scripts/gen-seed.mjs from content/rooms.json. Do not edit by hand.",
  "begin;",
];

for (const r of rooms) {
  lines.push(
    `insert into tense.rooms (id, order_index, title, subtitle, focus) values (${q(r.id)}, ${r.order_index}, ${q(r.title)}, ${q(r.subtitle)}, ${q(r.focus)})`,
    `  on conflict (id) do update set order_index = excluded.order_index, title = excluded.title, subtitle = excluded.subtitle, focus = excluded.focus;`,
  );
  for (const p of r.puzzles) {
    lines.push(
      `insert into tense.puzzles (id, room_id, order_index, scene_object, sentence_pre, sentence_post, verb_base, options, rule_feedback, translation, anim_trigger) values (${[
        q(p.id),
        q(r.id),
        p.order_index,
        q(p.scene_object),
        q(p.sentence_pre),
        q(p.sentence_post),
        q(p.verb_base),
        `${q(JSON.stringify(p.options))}::jsonb`,
        q(p.rule_feedback),
        q(p.translation),
        q(p.anim_trigger),
      ].join(", ")})`,
      `  on conflict (id) do update set room_id = excluded.room_id, order_index = excluded.order_index, scene_object = excluded.scene_object, sentence_pre = excluded.sentence_pre, sentence_post = excluded.sentence_post, verb_base = excluded.verb_base, options = excluded.options, rule_feedback = excluded.rule_feedback, translation = excluded.translation, anim_trigger = excluded.anim_trigger;`,
    );
  }
}

lines.push("commit;", "");
writeFileSync("supabase/seed.sql", lines.join("\n"));
console.log(`Wrote supabase/seed.sql (${rooms.length} rooms)`);
